spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/secureaudit
    username: secureaudit
    password: secureaudit
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${JWT_SECRET}
  expiry: ${JWT_EXPIRATION_SECONDS}

server:
  port: 8080

gcp:
  project-id: ${GCP_PROJECT_ID}
  kms:
    location: ${KMS_LOCATION:global}
    key-ring: ${KMS_KEY_RING}
    key-name: ${KMS_KEY_NAME}

